# Next.js Frontend
  - type: web
    name: fotoalbum_frontend
    runtime: docker
    dockerContext: .
    dockerfilePath: ./fotoalbum_frontend/Dockerfile
    envVars:
      - key: PORT
        value: 3000
      # 👇 Updated to match your Axios code 👇
      - key: NEXT_PUBLIC_BACKEND_URL
        fromService:
          name: fotoalbum_server
          type: web
          property: url