services:
  # 1. NestJS Auth Service
  - type: web
    name: fotoalbum_auth
    runtime: docker
    dockerContext: .
    dockerfilePath: ./fotoalbum_auth/Dockerfile
    envVars:
      - key: PORT
        value: 8888

  # 2. NestJS Server Service
  - type: web
    name: fotoalbum_server
    runtime: docker
    dockerContext: .
    dockerfilePath: ./fotoalbum_server/Dockerfile
    envVars:
      - key: PORT
        value: 3001

  # 3. Next.js Frontend
  - type: web
    name: fotoalbum_frontend
    runtime: docker
    dockerContext: .
    dockerfilePath: ./fotoalbum_frontend/Dockerfile
    envVars:
      - key: PORT
        value: 3000
      - key: NEXT_PUBLIC_API_URL
        fromService:
          name: fotoalbum_server
          type: web
          property: url