runtime: nodejs22
service: auth-service

beta_settings:
  cloud_sql_instances: "project-ef150698-8de6-49cc-9e8:us-central1:fotoalbum-auth"

env_variables:
  DB_HOST: "project-ef150698-8de6-49cc-9e8:us-central1:fotoalbum-auth"
  DB_USERNAME: "DB_USERNAME_PLACEHOLDER"
  DB_PASSWORD: "DB_PASSWORD_PLACEHOLDER"
  DB_DATABASE: "postgres"
  JWT_SECRET: "JWT_SECRET_PLACEHOLDER"
